name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install
        
      - name: Run test
        run: npm test

      - name: Build Docker Image
        run: docker build -t my-devops-app .

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment...[This is a simulated step]"
          docker run -d -p 3000:3000 my-devops-app